version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - D:/University/3course/semester2/Cross_platform/labs/mine/lab3/MySQL:/lab3.sql